controller_manager:
  ros__parameters:
    update_rate: 100
    diff_drive_controller:
      type: diff_drive_controller/DiffDriveController

diff_drive_controller:
  ros__parameters:
    left_wheel_names: ['front_left_wheel', 'rear_left_wheel']
    right_wheel_names: ['front_right_wheel', 'rear_right_wheel']
    wheel_separation: 0.58
    wheels_per_side: 2  # Enables skid-steer mode
    wheel_radius: 0.08
    publish_rate: 50.0
    odom_frame_id: odom
    base_frame_id: base_link
    enable_odom_tf: true
    linear:
      x:
        has_velocity_limits: true
        max_velocity: 2.0
    angular:
      z:
        has_velocity_limits: true
        max_velocity: 1.5